[2024-09-21T22:52:52.652+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_eval.getData manual__2024-09-21T22:52:49.074135+00:00 [queued]>
[2024-09-21T22:52:52.671+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_eval.getData manual__2024-09-21T22:52:49.074135+00:00 [queued]>
[2024-09-21T22:52:52.672+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-09-21T22:52:52.708+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): getData> on 2024-09-21 22:52:49.074135+00:00
[2024-09-21T22:52:52.717+0000] {standard_task_runner.py:60} INFO - Started process 2392 to run task
[2024-09-21T22:52:52.735+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_eval', 'getData', 'manual__2024-09-21T22:52:49.074135+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmp97mfa9pu']
[2024-09-21T22:52:52.738+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask getData
[2024-09-21T22:52:52.759+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-09-21T22:52:52.819+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_eval.getData manual__2024-09-21T22:52:49.074135+00:00 [running]> on host cc45b92b61e2
[2024-09-21T22:52:52.946+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_eval' AIRFLOW_CTX_TASK_ID='getData' AIRFLOW_CTX_EXECUTION_DATE='2024-09-21T22:52:49.074135+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-21T22:52:49.074135+00:00'
[2024-09-21T22:52:52.949+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-21T22:52:52.949+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/dags/app/getWeatherData.py']
[2024-09-21T22:52:52.971+0000] {subprocess.py:86} INFO - Output:
[2024-09-21T22:52:54.690+0000] {subprocess.py:93} INFO - /home/***/.local/lib/python3.8/site-packages/***/configuration.py:812 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-09-21T22:52:54.693+0000] {subprocess.py:93} INFO - /home/***/.local/lib/python3.8/site-packages/***/configuration.py:738 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-09-21T22:52:54.695+0000] {subprocess.py:93} INFO - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-09-21T22:52:54.923+0000] {subprocess.py:93} INFO - /home/***/.local/lib/python3.8/site-packages/***/models/base.py:71 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-09-21T22:52:56.073+0000] {subprocess.py:93} INFO - [[34m2024-09-21T22:52:56.072+0000[0m] {[34mcrypto.py:[0m82} WARNING[0m - empty cryptography key - values will not be stored encrypted.[0m
[2024-09-21T22:53:00.946+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-09-21T22:53:00.998+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dag_eval, task_id=getData, execution_date=20240921T225249, start_date=20240921T225252, end_date=20240921T225300
[2024-09-21T22:53:01.049+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-09-21T22:53:01.080+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
