[2024-09-22T11:00:56.956+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_eval.BestModel manual__2024-09-22T11:00:40.350339+00:00 [queued]>
[2024-09-22T11:00:56.968+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_eval.BestModel manual__2024-09-22T11:00:40.350339+00:00 [queued]>
[2024-09-22T11:00:56.969+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-09-22T11:00:56.987+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): BestModel> on 2024-09-22 11:00:40.350339+00:00
[2024-09-22T11:00:56.997+0000] {standard_task_runner.py:60} INFO - Started process 396 to run task
[2024-09-22T11:00:57.001+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_eval', 'BestModel', 'manual__2024-09-22T11:00:40.350339+00:00', '--job-id', '228', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpps49t48f']
[2024-09-22T11:00:57.003+0000] {standard_task_runner.py:88} INFO - Job 228: Subtask BestModel
[2024-09-22T11:00:57.020+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-09-22T11:00:57.076+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_eval.BestModel manual__2024-09-22T11:00:40.350339+00:00 [running]> on host cc45b92b61e2
[2024-09-22T11:00:57.199+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_eval' AIRFLOW_CTX_TASK_ID='BestModel' AIRFLOW_CTX_EXECUTION_DATE='2024-09-22T11:00:40.350339+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-22T11:00:40.350339+00:00'
[2024-09-22T11:00:57.253+0000] {logging_mixin.py:188} INFO - Scores: LR: -0.07240429794087395, DT: -3.936205050505047, RF: -4.4460175572949305
[2024-09-22T11:00:57.489+0000] {logging_mixin.py:188} INFO - RandomForestRegressor() saved at  /app/clean_data/best_model.pickle
[2024-09-22T11:00:57.614+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-09-22T11:00:57.628+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dag_eval, task_id=BestModel, execution_date=20240922T110040, start_date=20240922T110056, end_date=20240922T110057
[2024-09-22T11:00:57.655+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-09-22T11:00:57.680+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
