[2024-09-21T22:58:43.771+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_eval.getData manual__2024-09-21T22:58:40.447458+00:00 [queued]>
[2024-09-21T22:58:43.785+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_eval.getData manual__2024-09-21T22:58:40.447458+00:00 [queued]>
[2024-09-21T22:58:43.786+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-09-21T22:58:43.811+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): getData> on 2024-09-21 22:58:40.447458+00:00
[2024-09-21T22:58:43.819+0000] {standard_task_runner.py:60} INFO - Started process 148 to run task
[2024-09-21T22:58:43.822+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_eval', 'getData', 'manual__2024-09-21T22:58:40.447458+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpql26o1j2']
[2024-09-21T22:58:43.826+0000] {standard_task_runner.py:88} INFO - Job 8: Subtask getData
[2024-09-21T22:58:43.844+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-09-21T22:58:43.900+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_eval.getData manual__2024-09-21T22:58:40.447458+00:00 [running]> on host cc45b92b61e2
[2024-09-21T22:58:44.021+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_eval' AIRFLOW_CTX_TASK_ID='getData' AIRFLOW_CTX_EXECUTION_DATE='2024-09-21T22:58:40.447458+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-21T22:58:40.447458+00:00'
[2024-09-21T22:58:44.023+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-09-21T22:58:44.024+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/dags/app/getWeatherData.py']
[2024-09-21T22:58:44.043+0000] {subprocess.py:86} INFO - Output:
[2024-09-21T22:58:45.506+0000] {subprocess.py:93} INFO - /home/***/.local/lib/python3.8/site-packages/***/configuration.py:812 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-09-21T22:58:45.509+0000] {subprocess.py:93} INFO - /home/***/.local/lib/python3.8/site-packages/***/configuration.py:738 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-09-21T22:58:45.511+0000] {subprocess.py:93} INFO - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-09-21T22:58:45.771+0000] {subprocess.py:93} INFO - /home/***/.local/lib/python3.8/site-packages/***/models/base.py:71 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-09-21T22:58:47.029+0000] {subprocess.py:93} INFO - [[34m2024-09-21T22:58:47.028+0000[0m] {[34mcrypto.py:[0m82} WARNING[0m - empty cryptography key - values will not be stored encrypted.[0m
[2024-09-21T23:23:37.076+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-09-21T23:23:37.134+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dag_eval, task_id=getData, execution_date=20240921T225840, start_date=20240921T225843, end_date=20240921T232337
[2024-09-21T23:23:37.184+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-09-21T23:23:37.214+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
